---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcluster-config-overrides
data:
  # These values enable OIDC authentication and set the hostname for the API server
  values.yaml: |
    controlPlane:
      distro:
        k8s:
          apiServer:
            extraArgs:
              - "--oidc-issuer-url=https://myidp.example.org"
              - "--oidc-client-id=my-vcluster"
              - "--oidc-username-claim=preferred_username"
              - "--oidc-username-prefix=oidc:"
              - "--oidc-groups-claim=groups"
              - "--oidc-groups-prefix=oidc:"
              - "--oidc-signing-algs=RS256"
      ingress:
        host: my-cluster.k8s.example.org

    experimental:
      deploy:
        vcluster:
          manifests: |-
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: oidc:cluster-admin
            subjects:
              - apiGroup: rbac.authorization.k8s.io
                kind: Group
                name: oidc:my-vcluster
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
