---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcluster-config-defaults
data:
  # These values allow a vcluster to be deployed in a namespace with the restricted PSS
  values.yaml: |
    controlPlane:
      backingStore:
        etcd:
          deploy:
            enabled: true
            statefulSet:
              security:
                podSecurityContext:
                  fsGroup: 1000001
                containerSecurityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 10000001
                  seccompProfile:
                    type: RuntimeDefault
      distro:
        k8s:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000001
            seccompProfile:
              type: RuntimeDefault
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        spec:
          ingressClassName: nginx
      statefulSet:
        image:
          repository: loft-sh/vcluster-oss
        security:
          podSecurityContext:
            fsGroup: 1000001
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000001
            seccompProfile:
              type: RuntimeDefault

    integrations:
      metricsServer:
        enabled: true
        nodes: true
        pods: true

    policies:
      podSecurityStandard: privileged
      limitRange:
        enabled: true
      networkPolicy:
        enabled: true
      resourceQuota:
        enabled: true

    sync:
      fromHost:
        storageClasses:
          enabled: true
      toHost:
        configMaps:
          all: true
        networkPolicies:
          enabled: true
        secrets:
          all: true

    telemetry:
      enabled: false
