configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: vcluster-config-defaults
    files:
      - values.yaml=defaults.yaml

resources:
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml
