# The namespace to deploy the vcluster in
# This must match the name of the namespace in namespace.yaml
namespace: dawntest-cluster1

configMapGenerator:
  - name: vcluster-config-overrides
    files:
      - values.yaml=overrides.yaml

resources:
  - namespace.yaml
  - ../../base

patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: vcluster-config-overrides
          valuesKey: values.yaml
